CREATE TABLE CUSTOMER (
    CUSTNO CHAR(5) NOT NULL,
    CUSTNAME VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    INTERNAL CHAR(1) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    ZIP VARCHAR(10) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    CONTACT VARCHAR(30) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTNO)
);
