CREATE TABLE EMPLOYEE (
    EMPNO CHAR(5) NOT NULL,
    EMPNAME VARCHAR(30) NOT NULL,
    DEPARTMENT VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPNO)
);