CREATE TABLE EVENTREQUEST (
    EVENTNO CHAR(5) NOT NULL,
    CUSTNO CHAR(5) NOT NULL,
    FACNO CHAR(5) NOT NULL,
    DATEHELD DATE NOT NULL,
    DATEREQ DATE NOT NULL,
    DATEAUTH DATE,
    STATUS CHAR(20) NOT NULL,
    ESTCOST DECIMAL(8,2) NOT NULL,
    ESTAUDIENCE INTEGER NOT NULL,
    BUDNO CHAR(30),
  CONSTRAINT PK_EVENTREQUEST PRIMARY KEY (EVENTNO),
  CONSTRAINT FK_FACILITY FOREIGN KEY (FACNO) REFERENCES FACILITY (FACNO),
  CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER (CUSTNO)

);