CREATE TABLE EVENTPLANLINE (
  PLANNO CHAR(5) NOT NULL,
  LINENO CHAR(5) NOT NULL,
  TIMESTART TIMESTAMP NOT NULL,
  TIMEEND TIMESTAMP NOT NULL,
  NUMBERFLD INTEGER NOT NULL,
  LOCNO CHAR(5) NOT NULL,
  RESNO CHAR(5) NOT NULL,
  CONSTRAINT PK_EVENTPLANLINE PRIMARY KEY (PLANNO, LINENO),
  CONSTRAINT FK_EVENTPLAN FOREIGN KEY (PLANNO) REFERENCES EVENTPLAN (PLANNO),
  CONSTRAINT FK_LOCATION FOREIGN KEY (LOCNO) REFERENCES LOCATION (LOCNO),
  CONSTRAINT FK_RESOURCETBL FOREIGN KEY (RESNO) REFERENCES RESOURCETBL (RESNO)
);