CREATE TABLE LOCATION (
    LOCNO CHAR(5) NOT NULL,
    FACNO CHAR(10) NOT NULL,
    LOCNAME VARCHAR(30) NOT NULL,
    CONSTRAINT PK_LOCATION PRIMARY KEY (LOCNO),
    CONSTRAINT FK_FACILITY FOREIGN KEY (FACNO) REFERENCES FACILITY (FACNO)
);