SELECT EP.PLANNO, EP.EVENTNO, EP.WORKDATE, EP.ACTIVITY
FROM EVENTPLAN AS EP, EVENTREQUEST AS ER, FACILITY AS F
WHERE EP.EVENTNO = ER.EVENTNO AND
    ER.FACNO = F.FACNO AND
    F.FACNAME = 'Basketball arena' AND
    EP.WORKDATE BETWEEN '2018-12-01' AND '2018-12-31';