SELECT ER.EVENTNO, ER.DATEHELD, COUNT * AS EVENTPLANCOUNT
FROM EVENTREQUEST AS ER, EVENTPLAN AS EP
WHERE ER.EVENTNO = EP.EVENTNO AND
    EP.WORKDATE BETWEEN '2018-12-01' AND '2018-12-31'
GROUP BY ER.EVENTNO
HAVING EVENTPLANCOUNT > 1;